# Example configuration showing how to use different rollout backends

defaults:
  - judo

# You can test different backends by changing this configuration
controller_config_overrides:
  # For spot_door_box task, use C++ persistent backend (no ONNX issues)
  spot_door_box:
    rollout_backend: "cpp_persistent"  # Fast and reliable

  # Alternative: Test ONNX with a different task that matches the model
  # cartpole:
  #   rollout_backend: "onnx"
  #   onnx_model_path: "identity_network_pendulum.onnx"
  #   onnx_inference_frequency: 1

  # If you want to test ONNX with spot, you'd need a model trained for 66-dim input
  # spot_door_box:
  #   rollout_backend: "onnx_persistent"
  #   onnx_model_path: "identity_network_spot.onnx"  # This expects 51-dim, not 66-dim
  #   onnx_inference_frequency: 5
