# This pyproject.toml variant is used for building wheels in CI with cibuildwheel
# It uses scikit-build-core to compile the C++ extensions

[build-system]
requires = ["scikit-build-core[pyproject]", "pybind11", "mujoco", "numpy", "onnxruntime"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.source-dir = "judo_cpp"
wheel.packages = ["judo", "judo_cpp"]
cmake.build-type = "Release"
minimum-version = "0.4"
build-dir = "build/{wheel_tag}"

# Linux-specific configuration
[[tool.scikit-build.overrides]]
if.platform-system = "linux"
cmake.define.Eigen3_DIR = "/usr/local/share/eigen3/cmake"

# macOS-specific configuration
[[tool.scikit-build.overrides]]
if.platform-system = "darwin"
cmake.define.CMAKE_C_COMPILER = "/usr/bin/clang"
cmake.define.CMAKE_CXX_COMPILER = "/usr/bin/clang++"
