name: build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        os: [ubuntu-22.04]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ./src/mujoco_extensions
        python -m pip install -e .[dev]

    - name: Run tests and collect coverage
      run: pytest --cov=judo --cov-report=term --cov-report=xml -s

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5.0.6
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
