name: Code Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.47.0
          cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Restore typings cache
        uses: actions/cache@v4
        id: typings-cache
        with:
          path: typings
          key: typings-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

      - name: Generate stubs if cache miss
        if: steps.typings-cache.outputs.cache-hit != 'true'
        run: pixi run -e dev pybind11-stubgen mujoco -o typings/

      - name: Run Ruff Linter
        run: pixi run -e dev ruff check judo/ tests/ --output-format=github

      - name: Run Ruff Formatter
        run: pixi run -e dev ruff format judo/ tests/ --diff

      - name: Run Pyright
        run: pixi run -e dev pyright

      - name: Test with pytest
        run: pixi run -e dev pytest -rsx
